### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [Winderone/FireHoseSplurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by Winderone** [comment]
Thanks for the advice Ken, I added the viewport meta tag and it looks worlds better on mobile.

**Comment by kenmazaika** [comment]
Thumbs up.  Looks perfect.  :+1: Keep up the awesome work coding.
